AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  abnormal-values-stack

  Abnormal Sensor Data Processing Microservices
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs22.x
    Environment:
        Variables:
          LOGGER_LEVEL: debug
          TZ: Asia/Jerusalem
    Layers:
      - !Ref PinoLoggerLayer
    Architectures:
      - x86_64

Parameters:
  IngestStreamTopicArn:
    Type: String
    Description: ARN of the ingest stream SNS topic
    Default: arn:aws:sns:us-east-1:212712010886:sensors-data-ingest

Resources:
  # Lambda Layer for Pino Logger
  PinoLoggerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pino-logger-layer-abnormal
      Description: Pino logger configuration layer
      ContentUri: ../layers/pino-logger/
      CompatibleRuntimes:
        - nodejs22.x

  # SNS Topics for data streams (process streams)
  LowSensorDataTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: low-sensor-data
      DisplayName: Low Sensor Data Stream

  HighSensorDataTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: high-sensor-data
      DisplayName: High Sensor Data Stream

  # Abnormal Sensor Data Lambda Function
  AbnormalSensorDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: abnormal-sensor-data
      CodeUri: abnormal-sensor-data/
      Handler: app.lambdaHandler
      Events:
        IngestStreamSubscription:
          Type: SNS
          Properties:
            Topic: !Ref IngestStreamTopicArn
      Environment:
        Variables:
          LOW_SENSOR_DATA_TOPIC_ARN: !Ref LowSensorDataTopic
          HIGH_SENSOR_DATA_TOPIC_ARN: !Ref HighSensorDataTopic
          SENSOR_DATA_PROVIDER_FUNCTION_NAME: !Ref SensorDataProviderFunction
          STALE_TIME: 1
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt LowSensorDataTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt HighSensorDataTopic.TopicName
        - LambdaInvokePolicy:
            FunctionName: !Ref SensorDataProviderFunction

  # Sensor Data Provider Lambda Function
  SensorDataProviderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sensor-data-provider
      CodeUri: sensor-data-provider/
      Handler: app.handler

  # Low Data Processor Lambda Function
  LowDataProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: low-data-processor
      CodeUri: low-data-processor/
      Handler: app.lambdaHandler
      Events:
        LowSensorDataSubscription:
          Type: SNS
          Properties:
            Topic: !Ref LowSensorDataTopic

  # High Data Processor Lambda Function
  HighDataProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: high-data-processor
      CodeUri: high-data-processor/
      Handler: app.lambdaHandler
      Events:
        HighSensorDataSubscription:
          Type: SNS
          Properties:
            Topic: !Ref HighSensorDataTopic

Outputs:
  LowSensorDataTopicArn:
    Description: "ARN of Low Sensor Data SNS Topic"
    Value: !Ref LowSensorDataTopic
  
  HighSensorDataTopicArn:
    Description: "ARN of High Sensor Data SNS Topic"
    Value: !Ref HighSensorDataTopic
  
  AbnormalSensorDataFunctionArn:
    Description: "ARN of Abnormal Sensor Data Lambda Function"
    Value: !GetAtt AbnormalSensorDataFunction.Arn
  
  LowDataProcessorFunctionArn:
    Description: "ARN of Low Data Processor Lambda Function"
    Value: !GetAtt LowDataProcessorFunction.Arn
  
  HighDataProcessorFunctionArn:
    Description: "ARN of High Data Processor Lambda Function"
    Value: !GetAtt HighDataProcessorFunction.Arn

  SensorDataProviderFunctionArn:
    Description: "ARN of Sensor Data Provider Lambda Function"
    Value: !GetAtt SensorDataProviderFunction.Arn
